[build]
command = "pnpm install && pnpm run build"

[deploy]
startCommand = "node dist/src/main.js"
healthcheckPath = "/api/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 3

[env]
PNPM_VERSION = "8.6.0"
NODE_VERSION = "18" 